#!/bin/bash
# Run 10 copies of one task, for ten minutes, each using a different value of the environment variable SLURM_ARRAY_TASK_ID in the range 0 to 9
#SBATCH --tasks=1
#SBATCH --time=24:00:00
#SBATCH --array=0
#SBATCH --nodes=1

module load matlab

matlab -singleCompThread -nodisplay -r "train_data_awgn_iridis(8, 32, 32, 8, 10000, 1, 0, 0.5, 10, 0, 0); exit;"

#SBATCH --output=run1.out
#SBATCH --error=run1.err
